twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'assets/images': images
    globals:
        cars_pictures_path: '%cars_pictures_path%'
    form_themes: ['bootstrap_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true
